images_uploading/images/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from images import views


app_name = 'images'

urlpatterns = [
    path('', views.MainView.as_view(), name="index"),
    path('images/', views.ImageListView.as_view(), name='image_list'),
    path('images/<int:pk>/', views.ImageDetailView.as_view(), name='image_detail'),
    path('images/create/', views.ImageCreateView.as_view(), name='image_create'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images_uploading/images_uploading/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('images.urls')),
]

images_uploading/images/models.py
from django.db import models
from django.urls import reverse


class Image(models.Model):
    image = models.ImageField('Изображение', upload_to='images/images/')

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'

    def get_absolute_url(self):
        return reverse('images:image_detail', args=[str(self.id)])

    def __str__(self):
        return self.image.name.split('/')[-1]

images_uploading/images/forms.py
import io

import requests
from django import forms
from django.core.exceptions import ValidationError
from django.core.files.uploadedfile import InMemoryUploadedFile

from images import models


class ImageForm(forms.ModelForm):

    img_url = forms.URLField(label='Ссылка', required=False)
    image = forms.ImageField(required=False)

    class Meta:
        model = models.Image
        fields = ['image']

    def clean(self):
        cleaned_data = super(ImageForm, self).clean()
        img_url = cleaned_data.get('img_url')
        image = cleaned_data.get('image')

        if img_url and image:
            raise ValidationError('Нельзя указать ссылку из интренета и файл из компьютера одновременно')

        if not img_url and not image:
            raise ValidationError('Для загрузки картинки необходимо указать одно из значений')

        if img_url and not image:
            response = requests.get(img_url)
            filename = img_url.split('/')[-1]
            data = InMemoryUploadedFile(
                io.BytesIO(response.content),
                'image',
                filename,
                response.headers.get('Content-Type'),
                response.headers.get('Content-Length'),
                None
            )
            self.cleaned_data['image'] = self.fields['image'].clean(data)


class ImageSizeForm(forms.Form):
    width = forms.IntegerField(label='Ширина', required=False)
    height = forms.IntegerField(label='Высота', required=False)

images_uploading/images/views.py
import os

from django.views import generic
from django.views.generic import DetailView, ListView, TemplateView
from PIL import Image

from images import models, forms
from images_uploading.settings import MEDIA_URL, MEDIA_ROOT


class MainView(TemplateView):
    template_name = 'images/index.html'


class ImageListView(ListView):
    model = models.Image
    context_object_name = 'images'


class ImageDetailView(DetailView):
    model = models.Image
    context_object_name = 'image'

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        context = self.get_context_data(object=self.object)

        form = forms.ImageSizeForm(request.GET)
        context['form'] = form
        img_url = context['image'].image.url

        if form.is_valid():
            image = Image.open(context['image'].image.path)
            width = form.cleaned_data['width']
            height = form.cleaned_data['height']
            width = width if width else image.size[0]
            height = height if height else image.size[1]

            image_resize = image
            image_resize.thumbnail((width, height))

            img_name = context['image'].image.name.split('/')[-1]
            tmp_dir = os.path.join(*context['image'].image.name.split('/')[:-1], 'tmp')
            img_dir = os.path.join(MEDIA_ROOT, tmp_dir)

            os.makedirs(img_dir, exist_ok=True)

            resize_image_url = os.path.join(MEDIA_URL, tmp_dir, img_name)
            image_resize.save(os.path.join(img_dir, img_name))
            img_url = resize_image_url

        context['img_url'] = img_url

        return self.render_to_response(context)


class ImageCreateView(generic.CreateView):
    template_name = 'images/image_create.html'
    form_class = forms.ImageForm

images_uploading/images/templates/images/image_create.html
{% extends 'images/index.html' %}

{% block content %}
    <h1>Добавить изображение</h1>

    <form method="post" action="{% url 'images:image_create' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить изображение</button>
    </form>

    <div>
        <a href="{% url 'images:image_list'%}">К списку всех изображений</a>
    </div>
    <div>
        <a href="{% url 'images:index'%}">На главную</a>
    </div>

{% endblock %}

images_uploading/images/templates/images/image_detail.html
{% extends 'images/index.html' %}

{% block content %}
    <h1>{{ image }}</h1>

    <img src="{{ img_url }}" alt="{{ image }}">

    <div>
        <a href="{% url 'images:image_list'%}">К списку всех изображений</a>
    </div>
    <div>
        <a href="{% url 'images:index'%}">На главную</a>
    </div>
    <div>
        <a href="{% url 'images:image_create'%}">Добавить изображение</a>
    </div>

    <form method="get" action="{% url 'images:image_detail' pk=image.id %}">
        {{ form.as_p }}
        <button type="submit">Поменять размер изображения</button>
    </form>

{% endblock %}

images_uploading/images/templates/images/image_list.html
{% extends 'images/index.html' %}

{% block content %}
    <h1>Все изображения</h1>

    <ul>
    {% for image in images %}
        <li>
            <a href="{% url 'images:image_detail' pk=image.id %}">
                {{ image}}
            </a>
        </li>
    {% empty %}
        <li>Доступных изображений пока еще нету</li>
    {% endfor %}
    </ul>

    <div>
        <a href="{% url 'images:index'%}">На главную</a>
    </div>
    <div>
        <a href="{% url 'images:image_create'%}">Добавить изображение</a>
    </div>
{% endblock %}

images_uploading/images/templates/images/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Изображения</title>
</head>
<body>

    {% block content %}

        <h1>Сервис для добавления изображжения в базу</h1>
        <div>
            <a href="{% url 'images:image_list'%}">Посмотреть все изображения</a>.
        </div>
        <div>
            <a href="{% url 'images:image_create'%}">Добавить изображение</a>
        </div>

    {% endblock %}

</body>
</html>